export const ACTIONS_ADD_COMMENT = 'ACTIONS_ADD_COMMENT';
export const ACTIONS_DELETE_COMMENT = 'ACTIONS_DELETE_COMMENT';
export const ACTIONS_AUTHORIZATION_USER = 'ACTIONS_AUTHORIZATION_USER';
export const ACTIONS_MESSAGE_ERROR = 'ACTIONS_MESSAGE_ERROR';
export const ACTIONS_REDIRECT_TO_SEARCH = 'ACTIONS_REDIRECT_TO_SEARCH';
export const ACTIONS_ADD_SEARCH_STR = 'ACTIONS_ADD_SEARCH_STR';
export const ACTIONS_EDIT_NAME_USER = 'ACTIONS_EDIT_NAME_USER';