export const ACTIONS_ADD_COMMENT = 'ACTIONS_ADD_COMMENT';
export const ACTIONS_DELETE_COMMENT = 'ACTIONS_DELETE_COMMENT';
export const ACTIONS_AUTHORIZATION_USER = 'ACTIONS_AUTHORIZATION_USER';
export const ACTIONS_MESSAGE_ERROR = 'ACTIONS_MESSAGE_ERROR';